# Generated by Django 3.2 on 2022-11-09 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_information'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='student_name',
        ),
    ]
